<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deskripsi</name>
   <tag></tag>
   <elementGuidId>ec66ca42-684b-45be-890a-105c6b173f7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section/main/section/main/div/div[2]/form[1]/div/div[4]/div/div/div/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
